spring:
  application:
    name: fitness-java
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.163.7.156:64321/fitness?serverTimezone=Asia/Shanghai&characterEncoding=utf-8
    username: root
    password: X7#k9P$m2@qL!vWc
  jpa:
    show-sql: true
    database: mysql
    hibernate:
      ddl-auto: update
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

springdoc: # 生产记的关闭
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

wx:
  miniapp:
    appid: "213"
    appsecret: "123"

server:
  port: 8081
